### ISSUE TITLE
Latest build failing

### ISSUE THREAD

**Issue by AceCentury** [CS2103AUG2017-T10-B3/main#35]
Master branch is failing tests after merging from https://github.com/CS2103AUG2017-T10-B3/main/pull/34    

Pull request passes all tests.

Master build seems to be failing this particular test

_guitests.GuiRobot$EventTimeoutException at BrowserPanelTest.java:47_

Pull request did not modify the files related to the BrowserPanel or the BrowserPanelTest.

@yuheng222 Are you able to take a look? I think it might have something to do with your Google Maps redirect.

**Comment by yuheng222** [comment]
Thanks for the notice. 

I made some slight modifications to BrowserPanelTest.java and the latest build is fixed,
