### ISSUE TITLE
addListener in TagPane.java not working

### ISSUE THREAD

**Issue by WangJieee** [CS2103AUG2017-T10-B3/main#50]
I want to make the tags in the tagPane behave like the tags in PersonCard i.e adding or removing a tag can be shown accordingly. But it seems that the tag pane remains static even though I implement the bindListener method and I don't know where is the bug:(

Pls help!! T T

**Comment by AceCentury** [comment]
Are you able to merge your existing code into a new **branch** on the team repo? This is so that I am able to download the source files and help debug more easily.
