### ISSUE TITLE
Display scaling/resolution issue

### ISSUE THREAD

**Issue by khooroko** [CS2103AUG2017-T10-B3/main#74]
![image](https://user-images.githubusercontent.com/28438978/32362732-8700294a-c0a6-11e7-9b99-28b8e8adae1d.png)

It looks like this on my laptop, not sure if it is a problem on my end.

**Comment by AceCentury** [comment]
You can resize the views. Try hovering the cursor at the divider between the map and tag panel.

**Comment by Infinity-Ace** [comment]
It is normal. You can resize the tag panel pane by dragging the separator.
