### ISSUE TITLE
Bug: app fails to open after modifying data

### ISSUE THREAD

**Issue by khooroko** [CS2103AUG2017-T10-B3/main#82]
It seems to me that if I perform any action that changes the addressbook (`edit`, `removetag`, `addtag` etc) the app cannot be opened again until I delete the data folder

**Comment by AceCentury** [comment]
Release v1.3 of the app does not have this issue. Issue happens in release v1.4. I will attempt to do more digging to find out what is causing this.

**Comment by AceCentury** [comment]
@WangJieee Your merge might not have caused this issue, but the OutOfMemoryError is something you should still look at regardless: https://github.com/CS2103AUG2017-T10-B3/main/commit/803b2fee12fab68dfe496d401d6140ba728a808a

AppVeyor run: https://ci.appveyor.com/project/AceCentury/main/build/1.0.24

Out of memory fails twice, but passes on the third time.

**Comment by AceCentury** [comment]
@CS2103AUG2017-T10-B3/developers **master-backup** branch has been created. It is the point in time just before @WangJieee v1.4 PR was merged. For testing of your future PRs, it is advised to use this branch, but do not merge without peer reviews.

**Comment by AceCentury** [comment]
@yuheng222 Found the PR causing this issue: https://github.com/CS2103AUG2017-T10-B3/main/commit/e6513ed637ae3e4f08b42aa4a8f03870e11f684c

**Comment by yuheng222** [comment]
@AceCentury Thanks for pointing out the faulty commit. I have made some minor modifications to the code and the app works as normal now. This issue will be fixed by the next merge.

**Comment by yuheng222** [comment]
Issue has been resolved in the latest [merge.](https://github.com/CS2103AUG2017-T10-B3/main/pull/87)
